import { createClient } from "@/lib/supabase/server";
import type { Settings } from "@/types";

const defaults: Settings = {
  id: 1,
  site_name: "متجر لمعة للاكسسوارات المطلية",
  store_logo: null,
  hero_image: null,
  hero_image_mobile: null,
  hero_title: "اكتشفي تشكيلتنا الجديدة",
  hero_subtitle: "قطع مختارة بتفاصيل تليق بك",
  hero_cta_text: "تسوقي الآن",
  hero_cta_link: "/shop",
  hero_width: 1920,
  hero_height: 700,
  hero_show_cta: true,
  category_section_width: 1200,
  category_section_height: 200,
  category_item_size: 120,
  category_item_gap: 28,
  category_item_shape: "circle",
  announcement: null,
  whatsapp: null,
  phone: null,
  email: null,
  address: null,
  instagram: null,
  tiktok: null,
  snapchat: null,
  twitter: null,
  payment_instructions: "يرجى تحويل المبلغ إلى الحساب البنكي ثم إرسال إثبات التحويل عبر واتساب أو رفعه في الطلب.",
  bank_name: null,
  iban: null,
  account_name: null,
  shipping_fee: 25,
  free_shipping_threshold: 300,
  shipping_display_mode: "pickup",
  commercial_register: null,
  tax_number: null,
  footer_text: null,
  font_family: "cairo",
  base_font_size: 16,
  heading_scale: 1,
  primary_color: "#B08D57",
  accent_color: "#111111",
  background_color: "#F8F6F1",
  text_color: "#111111",
  card_radius: 16,
  header_footer_font_size: 13,
  currency_mark_url: "/currency-mark.svg",
  show_currency_mark: true,
  notifications_paused: false,
  footer_bg_color: "#1a1a1a",
  footer_text_color: "#a8a29e",
  footer_link_color: "#a8a29e",
  footer_link_hover_color: "#d4af37",
  footer_heading_color: "#f5f5f4",
  footer_border_color: "rgba(255,255,255,0.1)",
  footer_bottom_bg_color: "#1a1a1a",
  footer_bottom_text_color: "#78716c",
  footer_show_brand: true,
  footer_show_links: true,
  footer_show_contact: true,
  footer_links_json: null,
  // Brand section defaults
  footer_brand_bg_color: "#292524",
  footer_brand_padding_y: 48,
  footer_brand_logo_width: 120,
  footer_brand_logo_height: 0,
  footer_brand_logo_align: "center",
  footer_brand_logo_gap: 16,
  footer_brand_desc_size: 14,
  footer_brand_desc_color: "#a8a29e",
  footer_brand_desc_weight: 400,
  footer_brand_desc_align: "center",
  footer_brand_desc_max_width: 600,
  // Header defaults
  header_height: 64,
  header_padding_top: 0,
  header_padding_bottom: 0,
  header_gap: 8,
  header_logo_width: 0,
  header_logo_height: 0,
  header_logo_align: "start",
  header_bg_color: "#FAFAF9",
  header_text_color: "#111111",
  header_link_color: "#57534e",
  header_link_hover_color: "#B08D57",
  header_icon_color: "#111111",
  mobile_products_layout: "grid",
  mobile_products_allow_user_toggle: false,
};

export async function getSettings(): Promise<Settings> {
  try {
    const supabase = await createClient();
    const { data } = await supabase.from("settings").select("*").eq("id", 1).maybeSingle();
    if (data) return { ...defaults, ...data } as Settings;
  } catch {}
  return defaults;
}
